#!/usr/bin/env bash

set -euxo pipefail

BRANCH=$1
CHAIN=$2
DOMAIN=$3

if [[ ! -d ord ]]; then
  git clone https://github.com/c1r2y3p4t5o/ord-junkcoin.git
fi

cd ord

git fetch origin
git checkout -B $BRANCH
git reset --hard origin/$BRANCH
./deploy/setup $CHAIN $DOMAIN
